### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

### ISSUE THREAD

**Issue by arodzh-sudo** [lenaschimmel/sarscov2recombinants#7]
Getting this error while trying to run the program:

`Reading reference genome, lineage definitions...`
`Done.`
`Reading actual input.`
`Traceback (most recent call last):`
  `File "search_recombinants.py", line 539, in <module>`
  `  main()`
`  File "search_recombinants.py", line 96, in main`
`    all_samples = all_samples | read_samples`
`TypeError: unsupported operand type(s) for |: 'dict' and 'dict'`

**Comment by lenaschimmel** [comment]
Ah yes, this has already been reported as issue #6. I just pushed an update which hopefully fixes it.

If you still experience this problem, please re-open or comment.
